"""add post author

Revision ID: 03414fac27d3
Revises: d5427a0cc3d6
Create Date: 2022-03-13 18:54:03.725661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03414fac27d3'
down_revision = 'd5427a0cc3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
