"""update posts table

Revision ID: d5427a0cc3d6
Revises: ba45b2c60b4d
Create Date: 2022-03-13 10:59:13.427916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5427a0cc3d6'
down_revision = 'ba45b2c60b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'slug')
    op.drop_column('posts', 'date_posted')
    # ### end Alembic commands ###
